version: '3.8'

services:
  app:
    image: app:latest
    environment:
      DATABASE_URL: '${DATABASE_URL}'
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - app_storage:/usr/src/app
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - '3000' # internal port, not exposed to host
    healthcheck:
      test: ['CMD-SHELL', "psql ${DATABASE_URL} -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Additional HTTP health check
    extra_healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/api || exit 1']
      start_period: 30s
      interval: 20s
      timeout: 10s
      retries: 3

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '8000:80' # Expose port 80 on the host
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf # Bind mount your custom nginx.conf
  #   depends_on:
  #     - app # Wait for the app to start before starting nginx
  #   healthcheck:
  #     test: ['CMD-SHELL', 'curl -f http://localhost || exit 1']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  database:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '5050:80'

volumes:
  app_storage:
    driver: local
  pg_data:
    driver: local
  redis:
    driver: local
