version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    image: app:latest
    volumes:
      - app_storage:/usr/src/app
    ports:
      - '3000:3000' # internal port, not exposed to host
    depends_on:
      - redis
      - postgres

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '8000:80' # Expose port 80 on the host
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf # Bind mount your custom nginx.conf
  #   depends_on:
  #     - app # Wait for the app to start before starting nginx

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      DATABASE_URL: '${DATABASE_URL}'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '5050:80'

volumes:
  app_storage:
    driver: local
  pg_data:
    driver: local
  redis:
    driver: local
